all:
  hosts:
    node1:
      ansible_host: 192.168.1.11
      ansible_user: "{{ lookup('env', 'NODE_USER') | default('ubuntu') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
    node2:
      ansible_host: 192.168.1.12
      ansible_user: "{{ lookup('env', 'NODE_USER') | default('ubuntu') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
    node3:
      ansible_host: 192.168.1.13
      ansible_user: "{{ lookup('env', 'NODE_USER') | default('ubuntu') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}" 