---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: care-companion-platform
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.20.2
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://0.0.0.0:8000
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secretkey

            # ✅ FIXED: legal Secret key name
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow
                  key: MLFLOW_BACKEND_STORE_URI

          command: ["/bin/sh", "-c"]
          args:
            - |
              pip install psycopg2-binary boto3 &&
              mlflow server --backend-store-uri $POSTGRES_URI \
              --artifacts-destination s3://mlflow-artifacts/ --serve-artifacts --host 0.0.0.0 --port 8000 --app-name basic-auth

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: care-companion-platform
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  externalIPs:
    - {{ .Values.mlflow.externalIP }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow
  namespace: care-companion-platform
type: Opaque
stringData:
  MLFLOW_BACKEND_STORE_URI: postgresql://user:password@postgres/mlflowdb