{{- $node := .Values.blockStorage.node        | default "kvm-node-01" -}}
{{- $size := .Values.blockStorage.grafanaSize | default "4Gi" -}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
spec:
  storageClassName: local-block
  capacity:       { storage: {{ $size }} }
  accessModes:    [ReadWriteOnce]             
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/block/grafana                  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [ {{ $node | quote }} ]
