global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'sc10247@nyu.edu'  # Replace with your email
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'  # Replace with your SMTP server
        auth_username: 'alertmanager@example.com'
        auth_password: 'your-password'  # Replace with your SMTP password
        require_tls: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job'] 