# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory to /app
WORKDIR /app

# Install curl for health checks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copy the requirements.txt into the container at /app
COPY utils/requirements/inference_requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY src/inference_server /app
RUN mkdir -p /app/reference_data

# Expose the port on which the app will run
EXPOSE 5000

# Run the command to start the Fastapi server
CMD ["python","app.py"]