name: chi_tacc_services
services:
  ray-training:
    image: rayproject/ray:2.42.1-gpu
    container_name: ray-worker-1
    command: >
      /bin/sh -c "
      ray stop --force >/dev/null 2>&1 || true &&
      ray start --address=${KVM_FLOATING_IP}:6379 \
        --num-cpus=32 --num-gpus=1 --block"
    runtime: nvidia
    environment:
      - KVM_FLOATING_IP=${KVM_FLOATING_IP} 
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://${KVM_FLOATING_IP}:9000
      - MLFLOW_TRACKING_URI=http://${KVM_FLOATING_IP}:8000
      - MLFLOW_S3_ENDPOINT_URL=http://${KVM_FLOATING_IP}:9000
    shm_size: '12g'
    volumes:
      - /mnt/object/:/mnt/object/
    user: root

  ray-serving:
    image: rayproject/ray:2.42.1-gpu
    container_name: ray-worker-2
    command: >
      /bin/sh -c "
      ray stop --force >/dev/null 2>&1 || true &&
      ray start --address=${KVM_FLOATING_IP}:6379 \
        --num-cpus=32 --num-gpus=1 --block"
    runtime: nvidia
    environment:
      - KVM_FLOATING_IP=${KVM_FLOATING_IP}
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://${KVM_FLOATING_IP}:9000
      - MLFLOW_TRACKING_URI=http://${KVM_FLOATING_IP}:8000
      - MLFLOW_S3_ENDPOINT_URL=http://${KVM_FLOATING_IP}:9000
    shm_size: '12g'
    volumes:
      - /mnt/object/:/mnt/object/
    user: root