FROM quay.io/jupyter/pytorch-notebook:cuda12-latest

USER ${NB_UID}

WORKDIR /work/

COPY . .

RUN pip install --pre --no-cache-dir torch && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN pip install --pre --no-cache-dir -r requirements.txt && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
    
# Install MLFlow and pynvml library used by MLFlow for monitoring NVIDIA GPU
RUN pip install --pre --no-cache-dir pynvml && \
    pip install --pre --no-cache-dir mlflow && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"