FROM quay.io/jupyter/pytorch-notebook:cuda12-latest

USER ${NB_UID}

RUN pip install --pre --no-cache-dir torch && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN pip install --pre --no-cache-dir pynvml && \
    pip install --pre --no-cache-dir mlflow==2.20.2 && \
    pip install --pre --no-cache-dir ray==2.42.1 && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
