all:
  vars:
    ansible_ssh_common_args: '-o ConnectTimeout=30'
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o ConnectTimeout=30'
  hosts:
    node1:
      ansible_host: 192.168.1.11
      ansible_user: cc
    node2:
      ansible_host: 192.168.1.12
      ansible_user: cc
    node3:
      ansible_host: 192.168.1.13
      ansible_user: cc

