apiVersion: v2
name: mlflow
version: 1.0.0
dependencies:
  - name: postgresql
    version: "~16.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: postgres
  - name: kube-prometheus-stack
    version: 45.0.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
  - name: grafana
    version: 8.0.0
    repository: https://charts.bitnami.com/bitnami
    alias: grafana
