
name: Basic Runner Test

on:
  push:
    branches: [main]

jobs:
  test-runner:
    runs-on: self-hosted  

    steps:
      - name: Print Hello Message
        run: echo "✅ GitHub Actions runner is working!"

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la
